language:
    - cpp

compiler:
    - g++

before_install:
    - sudo apt-get install cmake
    - sudo apt-get install gfortran
    - git submodule update --init --recursive

script:
    - ./configure
    - make

